# 网站域名，比如 'www.apple.com' 或者 'twitter.com'
RABEL_HOST_NAME: 'idea.shandian.in'

# 系统邮件的发件地址，比如 'no-replya@twitter.com'
RABEL_SYSTEM_EMAIL: 'no-reply@idea.shandian.in'

# 使用 'rake secret' 命令来生成 secret token
SECRET_TOKEN: 'c174c11139a803e9b6054cf9f78ae25c8c13962010b9ae87ac7f72729d8c730b25132bc353e0cbf6abd84fa81c874de62e748bbb483ff4405f39723cc9b9c8fa'

# 请使用'网站名+ 随机数'替换 'example', 比如替换成 '_twitter_9527_session'
SESSION_KEY: '_xdbbs_9527_session'

# 缓存配置，默认情况下不需要修改
RABEL_MEMCACHED_SERVER: '127.0.0.1:11011'
RABEL_MEMCACHED_USERNAME: ''
RABEL_MEMCACHED_PASSWORD: ''
RABEL_MEMCACHED_NAMESPACE: 'example'

# 又拍云存储(www.upyun.com)配置

# 修改为 'on'，开启图片上传功能
RABEL_UPYUN_SWITCH: 'on'

# 操作员名称
RABEL_UPYUN_OP_NAME: 'tinyao'

# 操作员密码
RABEL_UPYUN_OP_PASSWORD: 'sdfhq,lxndy'

# 空间名称
RABEL_UPYUN_BUCKET: 'shandian-rabel'

# 空间域名
RABEL_UPYUN_BUCKET_DOMAIN: 'shandian-rabel.b0.upaiyun.com'

